### ISSUE TITLE
Support for Boss Death Action Log

### ISSUE THREAD

**Issue by redpawn96** [kurtekat/shaiya-episode-6#115]
As per checking game logs, server is not recording boss death related logs. I hope we can support this kind of feature, very helpful for boss timers.
Thanks sir kurtekat

**Comment by kurtekat** [comment]
You don't have to be formal when we talk. :P I posted a CT people can use to log boss death.

https://forum.shaiya.gg/threads/log-boss-respawn-in-the-actionlog-table.38/

Otherwise, we'd have to mod the gameLog service, which is something I don't want to do at this time. Here's the packet the game service sends to the gameLog service:

https://github.com/kurtekat/shaiya-episode-6/blob/main/shaiya/include/network/gameLog/incoming/0A00.h
