### ISSUE TITLE
item duration bug 

### ISSUE THREAD

**Issue by im-razor** [kurtekat/shaiya-episode-6#80]
I made a video for you to see the bugs
https://www.youtube.com/watch?v=jPOraaUT_5Q

To explain the problem, item durations do not work, when an expired item expires, it causes a ps_game crash when the char logs into the game. Duration for wings doesn't work at all. I tried with the original Shaiya PT client as I think the problem is on the client side, but the result is the same 
Additional information;
Range = 30 
ExtDuration= 1

 and I used all the sql procedures in the sql folder

**Comment by im-razor** [comment]
I also tried the same thing after deleting all the items in PS_GameData > dbo.CharItems, but this time ps_game did not crash, but when I clicked to log in to the character, it crashed and when I logged back into the game, I saw that the pet was deleted because it expired, so it worked, but the problem continues like this

**Comment by kurtekat** [comment]
the library only supports pets and costumes by default. did you attempt to make it support wings? 

range is server-side only. client-side you'd want to do this:
Duration = 2592000
ExtDuration = 1

**Comment by kurtekat** [comment]
as far as your crash goes, you're gonna have to build a debug version, attach vs to ps_game with the library project open, and send me some real data. it will show you exactly where it breaks.

**Comment by im-razor** [comment]
I have never tried to activate the duration for any item except pet, costume and wings

Except for the information I provided above for the client
Duration = 2592000
Duration is also true

for server side 
![pet range](https://github.com/kurtekat/shaiya-episode-6/assets/79925277/ef087d7b-f0a2-4538-8304-106a89872464)


I am using the file for ep6 that you shared as ps_game.exe as an extra.

also if you want I can share the log file that exists when there is a crash here or I can share the files I use with you.

**Comment by kurtekat** [comment]
> also if you want I can share the log file that exists when there is a crash here or I can share the files I use with you.

i'd rather you attached a debugger and see where it breaks. you can send the logs if you want, but i doubt it's gonna make any difference.

**Comment by im-razor** [comment]
First of all, I must say, I found the cause of the error.
Now I will explain the error after responding to your answer, 
I have not activated anything except your dll file. CT file or a dll is currently only your dll file active. 
The ps_game and ps_dbAgent I use are the files you shared, so we are using the same things, the only difference is the database, but it doesn't matter because I am using the SQL procedures you gave me again. (but again, I changed the database and got the same result again).
Now let's come to the error,
What causes the error is interestingly the armor we wear on it, if you are wearing any armor on you, this causes ps_game crash, but if you don't have any armor on you, this is not a problem and it deletes the item without any problem, watch the video completely and you will see the problem live. I have no idea how to solve this right now I just found the error

https://youtu.be/pCSsApMoW2Y

**Comment by kurtekat** [comment]
these videos are not showing me **where** the error occurs. i see you have visual studio running in the background, so i don't understand why you won't attach it to the process. don't send me another video. send me the information you see when it breaks. i cannot reproduce this issue, so please just do what i'm asking you to do. otherwise, i can't help you.

**Comment by im-razor** [comment]
[20240702_002542_ps_game.dmp](https://github.com/kurtekat/shaiya-episode-6/files/14466152/20240702_002542_ps_game.dmp)
[PS_DBAGENT__charsave.log](https://github.com/kurtekat/shaiya-episode-6/files/14466153/PS_DBAGENT__charsave.log)
[PS_DBAGENT__system.log](https://github.com/kurtekat/shaiya-episode-6/files/14466154/PS_DBAGENT__system.log)
[PS_GAME__system.log](https://github.com/kurtekat/shaiya-episode-6/files/14466155/PS_GAME__system.log)

[ps_dbAgent](https://github.com/kurtekat/shaiya-episode-6/blob/main/server/sdev-db/bin/ps_dbAgent.exe)
[ps_game](https://github.com/kurtekat/shaiya-episode-6/blob/main/server/sdev/bin/v2/ps_game.exe)

[dll.zip](https://github.com/kurtekat/shaiya-episode-6/files/14466205/dll.zip)

**Comment by kurtekat** [comment]
i think the one that posted issue #79 was having the same issue. that's why i marked this one as a duplicate.

i did manage to find the access violation. it's not in the item duration code but it is related, which explains why removing it made the bug go away. it's actually the synergy code that breaks. i don't feel like trying to explain how the two are related.

i found a second issue that originates from the same place as the first issue. i don't think i will be able to work around this bug, so i will more than likely remove the item duration feature.

**Comment by kurtekat** [comment]
i decided to remove the duration code. the problem should be solved.

https://github.com/kurtekat/shaiya-episode-6/releases/tag/v1.4.0

**Comment by im-razor** [comment]
> i think the one that posted issue #79 was having the same problem. that's why i marked this one as a duplicate.
> 
> i did manage to find the access violation. it's not in the item duration code but it is related, which explains why removing it made the bug go away. it's actually the synergy code that breaks. i don't feel like trying to explain how the two are related.

The item duration was working for shen1, yes it had errors but it was working. One of the reasons I used your library was actually because it worked fine. If you explain what it has to do with the synergy code and if necessary I am willing to not use synergy but I will try to make it work. I just ask you to explain where this conflicts

**Comment by kurtekat** [comment]
> The item duration was working for shen1, yes it had errors but it was working.

i think you'd be better off doing it however he did it.

> I just ask you to explain where this conflicts

if you would have attached a debugger like i asked you too, you would know.

> I will try to make it work

it's been nothing but problems from the start. i chose to remove it for several reasons; not because i couldn't make it work. the access violation easy to fix. the point is: it shouldn't have happened at all. this library has to be reliable.
